// ---------------------------------------------------------------------------------------------------------------------
// <copyright file="DetermineTranslatableDocumentsStage.cs" company="Justin Rockwood">
//   Copyright (c) Justin Rockwood. All Rights Reserved. Licensed under the Apache License, Version 2.0. See
//   LICENSE.txt in the project root for license information.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------------

namespace Desalt.Core.CompilerStages
{
    using System.Collections.Immutable;
    using System.Linq;
    using System.Text.RegularExpressions;
    using System.Threading;
    using System.Threading.Tasks;
    using Desalt.Core.Options;
    using Desalt.Core.Pipeline;
    using Desalt.Core.Translation;
    using Microsoft.CodeAnalysis;

    /// <summary>
    /// Pipeline stage that takes a C# project and determines which documents are translatable to TypeScript.
    /// </summary>
    internal class DetermineTranslatableDocumentsStage
        : PipelineStage<Project, ImmutableArray<DocumentTranslationContext>>
    {
        // The C# MSBuild process automatically generates an AssemblyAttributes.cs file for .NET Framework projects. It
        // doesn't need to be translated and it causes errors when trying to access that file simultaneously from
        // different threads.
        private static readonly Regex s_autoGeneratedAssemblyAttributesPattern = new Regex(
            @".*\.NETFramework,Version=.*AssemblyAttributes\.cs",
            RegexOptions.CultureInvariant | RegexOptions.Singleline);

        /// <summary>
        /// Executes the pipeline stage.
        /// </summary>
        /// <param name="input">The input to the stage.</param>
        /// <param name="options">The compiler options to use.</param>
        /// <param name="cancellationToken">
        /// An optional <see cref="CancellationToken"/> allowing the execution to be canceled.
        /// </param>
        /// <returns>The result of the stage.</returns>
        public override async Task<IExtendedResult<ImmutableArray<DocumentTranslationContext>>> ExecuteAsync(
            Project input,
            CompilerOptions options,
            CancellationToken cancellationToken = default)
        {
            var tasks = input.Documents.Where(doc => !s_autoGeneratedAssemblyAttributesPattern.IsMatch(doc.Name))
                .Select(document => DocumentTranslationContext.TryCreateAsync(document, options, cancellationToken));

            IExtendedResult<DocumentTranslationContext?>[] results = await Task.WhenAll(tasks);

            var onlyValidDocuments = results.Where(x => x.Result != null).Select(x => x.Result!).ToImmutableArray();
            var mergedDiagnostics = results.SelectMany(result => result.Diagnostics);

            return new ExtendedResult<ImmutableArray<DocumentTranslationContext>>(onlyValidDocuments, mergedDiagnostics);
        }
    }
}
